### ISSUE TITLE
Reset the values to null for “Show Total Cash Held” and “Press to Collect Cash” when the Maintainer successfully pushes “Press Here When Finished”

### ISSUE THREAD

**Issue by E0146954** [Monalisa93/SCM_FT07#1]
The simulation currently does not clear the values on the completion of a Maintenance session. Upon a subsequent re-login to the Maintenance Panel in the same session, the cash previously held and already collected, persists in display. This sometimes causes confusion to Maintainer.

**Comment by vipul-zambare006** [comment]
Fixed this issue with codes added in MaintainanceController. Kindly test.

**Comment by E0146954** [comment]
Issue is no longer seen and Verified as issue is fixed
