### ISSUE TITLE
The system is required to provide an at-a-glance display of the cash amount available, by denomination, for collection by the Maintainer.

### ISSUE THREAD

**Issue by E0146954** [Monalisa93/SCM_FT07#2]
The system is required to provide an at-a-glance display of the cash amount available, by denomination, for collection by the Maintainer. This will enable the Maintainer to readily tally the total cash collected and the total number of coins by denomination displayed in “Show Total Cash Held” and “Press to Collect Cash” when pressed, thus leaving no room for dispute over system errors.

**Comment by RachelGnanaraj** [comment]
Added Enhancement features

**Comment by E0146954** [comment]
Verified the enhancement and closed the status.
